install-deadline-worker

diff --git a/modules/firehawk-ami/scripts/install-deadlinedb b/modules/firehawk-ami/scripts/install-deadlinedb
--- a/modules/firehawk-ami/scripts/install-deadlinedb
+++ b/modules/firehawk-ami/scripts/install-deadlinedb
@@ -76,6 +76,19 @@ function assert_not_empty {
   fi
 }
 
+function assert_either_or {
+  local -r arg1_name="$1"
+  local -r arg1_value="$2"
+  local -r arg2_name="$3"
+  local -r arg2_value="$4"
+
+  if [[ -z "$arg1_value" && -z "$arg2_value" ]]; then
+    log_error "Either the value for '$arg1_name' or '$arg2_name' must be passed, both cannot be empty"
+    print_usage
+    exit 1
+  fi
+}
+
 # A retry function that attempts to run a command a number of times and returns the output
 function retry {
   local -r cmd="$1"
@@ -689,6 +702,48 @@ function install_rcs_generate_certs {
   # --proxycertificatepassword avaultpassword
 }
 
+function install_worker {
+  local -r deadline_installer_dir="$1"
+  local -r deadline_client_installer_filename="$2"
+  # local -r deadline_certificates_location="$3"
+  local -r deadline_client_certificates_location="$4"
+  # local -r deadline_client_certificate="$5"
+  local -r deadline_proxy_certificate="$6"
+  local -r deadlineuser_name="$7"
+  local -r httpport="$8"
+  local -r proxyport="$9"
+  local -r deadline_proxy_root_dir="${10}"
+  local -r skip_install_packages="${11}"
+  # local -r server_cert_basename="${12}"
+
+  # Directories and Permissions
+  if [[ "$skip_install_packages" == "false" ]]; then
+    echo "...Install packages for Deadline RCS"
+    sudo apt-get install -y xdg-utils
+    sudo apt-get install -y lsb # required for render nodes as well
+  fi
+  sudo mkdir -p /usr/share/desktop-directories
+
+  echo "...Installing Deadline Client: Worker"
+  # Install Client:
+  # Deadline Worker
+  sudo $deadline_installer_dir/$deadline_client_installer_filename \
+  --mode unattended \
+  --launcherdaemon true \
+  --debuglevel 2 \
+  --prefix /opt/Thinkbox/Deadline10 \
+  --connectiontype Remote \
+  --noguimode true \
+  --licensemode UsageBased \
+  --daemonuser "$deadlineuser_name" \
+  --httpport $httpport \
+  --tlsport $proxyport \
+  --enabletls true \
+  --slavestartup true \
+  --proxyrootdir $deadline_proxy_root_dir \
+  --proxycertificate $deadline_client_certificates_location/$deadline_proxy_certificate
+}
+
 function configure_deadline {
   echo "...Configure Deadline.ini"
   local -r deadline_proxy_root_dir="$1"
@@ -736,6 +791,7 @@ function set_hostname {
 
 function options { # Not all defaults are available as args, however the script has been built to easily alter this.
   local installers_bucket=""
+  local db_host_name=""
   local deadlineuser_name="$DEFAULT_DEADLINEUSER_NAME"
   local skip_certgen_during_install="false"
   local skip_certgen_during_rcs_install="false"
@@ -753,6 +809,7 @@ function options { # Not all defaults are available as args, however the script 
   local skip_install_packages="false"
   local skip_install_db="false"
   local skip_install_rcs="false"
+  local install_worker="false"
   local skip_install_validation="false"
 
   while [[ $# > 0 ]]; do
@@ -787,6 +844,9 @@ function options { # Not all defaults are available as args, however the script 
       --skip-install-rcs)
         skip_install_rcs="true"
         ;;
+      --install-worker)
+        install_worker="true"
+        ;;
       --post-certgen-db)
         post_certgen_db="true"
         ;;
@@ -817,14 +877,18 @@ function options { # Not all defaults are available as args, however the script 
   done
 
   assert_not_empty "--deadline-version" "$deadline_version"
-  assert_not_empty "--db-host-name" "$db_host_name"
+  assert_either_or "--db-host-name" "$db_host_name" "--install-worker" "$install_worker" # db host name not required when installing worker
+
+  if [[ "$install_worker" == "true" ]]; then # if installing the worker, disable db and rcs options
+    skip_install_db="true"
+    skip_install_rcs="true"
+  fi
 
   # Implicit vars
   cert_org="Deadline10Installer"
   cert_ou="Deadline10MongoDB"
   rcs_cert_ou="Deadline10ConnServer"
-  server_cert_basename="$db_host_name"
-  deadline_proxy_root_dir="$db_host_name:$proxyport"
+
   deadline_client_certificate_basename="${deadline_client_certificate%.*}"
   deadline_linux_installers_tar="/tmp/Deadline-${deadline_version}-linux-installers.tar"
   deadline_linux_installers_filename="$(basename $deadline_linux_installers_tar)"
@@ -837,7 +901,13 @@ function options { # Not all defaults are available as args, however the script 
   deadline_certificates_location="/opt/Thinkbox/DeadlineDatabase10/certs"
   deadline_client_certificates_location="/opt/Thinkbox/certs"
 
-  set_hostname $db_host_name
+  if [[ ! -z "$db_host_name" ]]; then
+    set_hostname $db_host_name # The db requires a host name for other clients to know how to find the service.
+
+    server_cert_basename="$db_host_name"
+    deadline_proxy_root_dir="$db_host_name:$proxyport"
+  fi
+
 
   # Downloads
   if [[ "$skip_download_installers" == "false" ]]; then
@@ -870,6 +940,11 @@ function options { # Not all defaults are available as args, however the script 
       install_rcs_no_generate_certs "$deadline_installer_dir" "$deadline_client_installer_filename" "$deadline_certificates_location" "$deadline_client_certificates_location" "$deadline_client_certificate" "$deadline_proxy_certificate" "$deadlineuser_name" "$httpport" "$proxyport" "$deadline_proxy_root_dir" "$skip_install_packages" "$server_cert_basename"
     fi
     configure_deadline "$deadline_proxy_root_dir" "$deadline_certificates_location" "$deadline_client_certificate" "$deadline_client_certificates_location" "$deadline_proxy_certificate"
+  fi
+
+  # Install Worker
+  if [[ "$install_worker" == "true" ]]; then
+    install_worker "$deadline_installer_dir" "$deadline_client_installer_filename" "$deadline_certificates_location" "$deadline_client_certificates_location" "$deadline_client_certificate" "$deadline_proxy_certificate" "$deadlineuser_name" "$httpport" "$proxyport" "$deadline_proxy_root_dir" "$skip_install_packages"
   fi
 
   # Generate certs seperately
