auto format

diff --git a/scripts/install-packages b/scripts/install-packages
--- a/scripts/install-packages
+++ b/scripts/install-packages
@@ -9,16 +9,46 @@ packer_version="1.7.2"
 set -e
 set -x
 
-SOURCE=${BASH_SOURCE[0]} # resolve the script dir even if a symlink is used to this script
+SOURCE=${BASH_SOURCE[0]}   # resolve the script dir even if a symlink is used to this script
 while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
-  DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
-  SOURCE=$(readlink "$SOURCE")
-  [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
+    DIR=$(cd -P "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd)
+    SOURCE=$(readlink "$SOURCE")
+    [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
 done
-SCRIPTDIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
+SCRIPTDIR=$(cd -P "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd)
 cd $SCRIPTDIR
 
 SUDOCMD="" # replace with text sudo to use elevated permissions
+
+function log {
+    local -r level="$1"
+    local -r message="$2"
+    local -r timestamp=$(date +"%Y-%m-%d %H:%M:%S")
+    echo >&2 -e "${timestamp} [${level}] [$SCRIPT_NAME] ${message}"
+}
+
+function log_info {
+    local -r message="$1"
+    log "INFO" "$message"
+}
+
+function log_warn {
+    local -r message="$1"
+    log "WARN" "$message"
+}
+
+function log_error {
+    local -r message="$1"
+    log "ERROR" "$message"
+}
+
+function has_yum {
+    [[ -n "$(command -v yum)" ]]
+}
+
+function has_apt_get {
+    [[ -n "$(command -v apt-get)" ]]
+}
 
 # $SUDOCMD yum install -y sudo
 # # This fixes yum update problems with codebuild
@@ -28,25 +58,37 @@ SUDOCMD="" # replace with text sudo to use elevated permissions
 # $SUDOCMD rm -rf /var/cache/yum
 # $SUDOCMD yum update -y
 
-$SUDOCMD yum install -y jq openssl python python3.8 python3-pip # for a specific python version - https://realpython.com/intro-to-pyenv/
+log_info "Installing dependencies"
+
+if has_apt_get; then
+    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y git jq openssl python python3.8 python3-pip
+    LC_ALL=C && sudo pip install boto3
+elif has_yum; then
+    yum install -y git jq openssl python python3.8 python3-pip
+    LC_ALL=C && pip install boto3
+else
+    log_error "Could not find apt-get or yum. Cannot install dependencies on this OS."
+    exit 1
+fi
+
 mkdir -p $SCRIPTDIR/tmp
 
-#: Codebuild requires python 3.8 instead of python 3.7 used in the amis for ansible to work. 
+#: Codebuild requires python 3.8 instead of python 3.7 used in the amis for ansible to work.
 
 # curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
 # sudo unzip awscliv2.zip
 # sudo ./aws/install
 # && python3.8 -m pip install --user typing_extensions --upgrade \
 
-python3.8 -m pip install --upgrade pip \
-    && python3.8 -m pip install --user "ansible==5.9.0" \
-    && python3.8 -m pip install --user boto3 botocore \
-    && export PATH=$PATH:/root/.local/bin \
-    && ansible --version
+python3.8 -m pip install --upgrade pip &&
+    python3.8 -m pip install --user "ansible==5.9.0" &&
+    python3.8 -m pip install --user boto3 botocore &&
+    export PATH=$PATH:/root/.local/bin &&
+    ansible --version
 
 # ansible [core 2.12.6]
 
-if terraform --version 2> /dev/null | grep -nq "Terraform v${terraform_version}"; then
+if terraform --version 2>/dev/null | grep -nq "Terraform v${terraform_version}"; then
     echo 'terraform already installed'
 else
     wget https://releases.hashicorp.com/terraform/${terraform_version}/terraform_${terraform_version}_linux_amd64.zip -P /tmp/ --quiet # Get terraform
@@ -58,7 +100,7 @@ wget https://releases.hashicorp.com/packer/${packer_version}/packer_${packer_ver
 $SUDOCMD unzip /tmp/packer_${packer_version}_linux_amd64.zip -d /tmp/
 $SUDOCMD mv /tmp/packer /usr/local/bin/.
 
-if terragrunt --version 2> /dev/null | grep -nq "terragrunt version v${terragrunt_version}"; then
+if terragrunt --version 2>/dev/null | grep -nq "terragrunt version v${terragrunt_version}"; then
     echo 'Terragrunt already installed'
 else
     wget https://github.com/gruntwork-io/terragrunt/releases/download/v${terragrunt_version}/terragrunt_linux_386 -P /tmp/ --quiet # Get Terragrunt
